[theme]
primaryColor = "#FFEB3B"  # Matches the yellow color used in your logo
backgroundColor = "#000000"  # Matches the black sidebar background
secondaryBackgroundColor = "#FFFFFF"  # Matches the white main content area background
textColor = "#FFFFFF"  # Text color set to white to match sidebar text
font = "sans serif"  # Helvetica, Arial fallback

[server]
headless = true

[browser]
gatherUsageStats = false
