<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sidebar Visualization</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            font-family: Helvetica, Arial, sans-serif;
        }
        .flex {
            display: flex;
        }
        .h-screen {
            height: 100vh;
        }
        .sidebar {
            width: 256px;
            background-color: black;
            color: white;
            display: flex;
            flex-direction: column;
        }
        .logo {
            padding: 24px;
            border-bottom: 1px solid white;
        }
        .logo-box {
            width: 64px;
            height: 64px;
            border: 2px solid white;
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 16px;
        }
        .logo-letter {
            font-size: 24px;
            font-weight: bold;
        }
        .nav {
            flex: 1;
            padding: 16px;
        }
        .nav-item {
            display: flex;
            align-items: center;
            padding: 8px;
            border-radius: 8px;
            transition: background-color 0.3s;
        }
        .nav-item:hover {
            background-color: #333;
        }
        .nav-letter {
            font-size: 36px;
            font-weight: bold;
            margin-right: 12px;
        }
        .main-content {
            flex: 1;
            padding: 32px;
            background-color: white;
        }
    </style>
</head>
<body>
    <div class="flex h-screen">
        <div class="sidebar">
            <div class="logo">
                <div class="logo-box">
                    <span class="logo-letter" style="color: #FFEB3B;">N</span>
                    <span class="logo-letter" style="color: #4CAF50;">E</span>
                    <span class="logo-letter" style="color: #E91E63;">X</span>
                    <span class="logo-letter" style="color: #F44336;">T</span>
                </div>
            </div>
            <nav class="nav">
                <div class="nav-item">
                    <span class="nav-letter" style="color: #F44336;">H</span>
                    <span class="nav-letter" style="color: #FFEB3B;">O</span>
                    <span class="nav-letter" style="color: #4CAF50;">M</span>
                    <span class="nav-letter" style="color: #E91E63;">E</span>
                </div>
            </nav>
        </div>
        <div class="main-content">
            <h2 style="font-size: 24px; font-weight: bold; margin-bottom: 16px;">Main Content Area</h2>
            <p>Your app content goes here.</p>
        </div>
    </div>
</body>
</html>
